 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 135-655-580
128.142.243.211 - - [20/Apr/2017 15:33:59] "GET / HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:33:59] "POST / HTTP/1.1" 405 -
128.142.243.211 - - [20/Apr/2017 15:34:23] "POST /add_data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/app/newExample.py", line 236, in add_data
    input_data=json.loads(request.data)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 185, in JSONObject
    raise ValueError(errmsg("Expecting object", s, end))
ValueError: Expecting object: line 1 column 16 (char 16)
128.142.243.211 - - [20/Apr/2017 15:34:37] "GET / HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:35:16] "GET /update HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:35:38] "GET /update/ HTTP/1.1" 404 -
128.142.243.211 - - [20/Apr/2017 15:37:56] "GET /test/ HTTP/1.1" 404 -
128.142.243.211 - - [20/Apr/2017 15:38:55] "GET /test?as HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:39:06] "GET /test? HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:39:23] "GET /query?a HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:39:23] "GET /static/query.js HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 15:47:01] "GET / HTTP/1.1" 304 -
128.142.243.211 - - [20/Apr/2017 15:49:54] "GET /search1/DAS/SingleElectron HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 17:07:09] "GET /update/ HTTP/1.1" 404 -
128.142.243.211 - - [20/Apr/2017 17:07:14] "GET /update? HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 19:57:31] "GET / HTTP/1.1" 200 -
128.142.243.211 - - [20/Apr/2017 19:57:31] "POST / HTTP/1.1" 405 -
128.142.243.211 - - [20/Apr/2017 19:57:55] "POST /add_data HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/app/newExample.py", line 236, in add_data
    input_data=json.loads(request.data)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 336, in raw_decode
    obj, end = self._scanner.iterscan(s, **kw).next()
  File "/usr/lib64/python2.6/json/scanner.py", line 55, in iterscan
    rval, next_pos = action(m, context)
  File "/usr/lib64/python2.6/json/decoder.py", line 185, in JSONObject
    raise ValueError(errmsg("Expecting object", s, end))
ValueError: Expecting object: line 1 column 16 (char 16)
128.142.243.211 - - [20/Apr/2017 20:08:28] "GET /update HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 04:03:46] "GET /search1/DAS/BBbarDMJets_pseudo_LO_Mchi-50_Mphi-10_TuneCUETP8M1_13TeV-madgraph-pythia8 HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 07:41:29] "GET /search1/DAS/HeavyNeutrino_trilepton_M-1_V-0p01_2l_NLO HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 07:42:06] "GET /search1/DAS/HeavyNeutrino_trilepton_M-1_V-0p01_mu_NLO HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 07:42:08] "GET /search1/DAS/HeavyNeutrino_trilepton_M-1_V-0p01_mu_NLO HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 08:41:45] "GET / HTTP/1.1" 200 -
128.142.243.211 - - [21/Apr/2017 08:41:47] "GET /query HTTP/1.1" 304 -
128.142.243.211 - - [21/Apr/2017 08:41:47] "GET /static/query.js HTTP/1.1" 304 -
